### ISSUE TITLE
Minor correction of a comment

### ISSUE THREAD

**Issue by AmirHossein-SayyadAbdi** [tlaplus/Examples#13]
Hi, I believe the comment in the spec [Bakery.tla](https://github.com/tlaplus/Examples/blob/master/specifications/Bakery-Boulangerie/Bakery.tla) that says "_MutualExclusion asserts that two distinct processes are in their critical sections._" is problematic, because no two distinct processes are allowed to be in the critical sections at the same time.

**Comment by muenchnerkindl** [comment]
Thanks for spotting this – I fixed the typo.
