### ISSUE TITLE
GameOfLife spec minor improvement possible?

### ISSUE THREAD

**Issue by ajrouvoet** [tlaplus/Examples#154]
As a complete TLA beginner I opened the GOL spec and I noticed that `TypeOK` and `Init` are identically defined but only the latter is used. Does this have a purpose or is this a slight oversight and would it make more sense to---for example---drop `TypeOk`? 

https://github.com/tlaplus/Examples/blob/f532f0ac4e44b97edd939f73e1caf8b4071cf419/specifications/GameOfLife/GameOfLife.tla#L17

It is perhaps superficial, but given that these specs serve for education purposes it might be worth addressing.

**Comment by ahelwer** [comment]
`TypeOK` is the type invariant and is marked as invariant to check in `GameOfLife.cfg`. Type invariants are broad statements about what sets each variable can range across during the execution of the system.

**Comment by lemmy** [comment]
`TypeOK` is referenced by the .cfg and checked as an invariants.

https://github.com/tlaplus/Examples/blob/f532f0ac4e44b97edd939f73e1caf8b4071cf419/specifications/GameOfLife/GameOfLife.cfg#L2C1-L2C17

**Comment by ajrouvoet** [comment]
Ah, clear! Thanks for clarifying!On 30 Oct 2024, at 16:19, Andrew Helwer ***@***.***> wrote:﻿
TypeOK is the type invariant and is marked as invariant to check in GameOfLife.cfg. Type invariants are broad statements about what sets each variable can range across during the execution of the system.
