### ISSUE TITLE
Add support for Github Codespaces

### ISSUE THREAD

**Issue by lemmy** [tlaplus/Examples#33]
https://github.com/tlaplus/Examples/commit/4686a0be8af77260a27351cad2491873ac124d60 adds rudimentary support for Github Codespaces.

TODOs:
* Include the latest version of TLA+ vscode extension (https://github.com/lemmy/vscode-tlaplus/releases which comes with the debugger?)
* Integrate Apalache (https://github.com/informalsystems/apalache/issues/716)
```shell
## Waiting for a stable URL.
apt-get install libz3-java libz3-jni libz3-dev libz3-4
mkdir apalache && cd apalache
wget https://github.com/informalsystems/apalache/releases/latest/download/apalache-v0.15.1.tgz
tar xvfz apalache-v0.15.1.tgz
```
* ~~Consider including the latest version of CommunityModules (e.g. EWD998 Utils.tla would conflict)~~
```
https://github.com/tlaplus/CommunityModules/releases/latest/download/CommunityModules-deps.jar
```

**Comment by lemmy** [comment]
@ShonFeder Do you guys want to add support for Apalache (as per above), and provide `MC.tla` for those examples that work with Apalache?

**Comment by shonfeder** [comment]
Hi, @lemmy. We are now publishing a stable URL for our releases: https://github.com/informalsystems/apalache/releases/latest/download/apalache.tgz

> provide MC.tla for those examples that work with Apalache?

I'm not sure where those files would go in this repository. Could you elaborate a bit?

Thanks!

**Comment by lemmy** [comment]
The scripting would go to https://github.com/tlaplus/Examples/blob/616c4c2e00dd7084c623d1dcc83b140279652fb4/.devcontainer/devcontainer.json#L16  However, it occurred to me that -due to type annotations being mandatory in Apalache now- none of the examples will work.  Thus, not terribly useful for users.

**Comment by lemmy** [comment]
https://github.com/tlaplus/Examples/commit/4309acfaeee000924413075e605606d13d3d13c2
