### ISSUE TITLE
How do I create .cfg files?

### ISSUE THREAD

**Issue by JordyMoos** [tlaplus/Examples#6]
I noticed that some examples have .cfg files. Does anyone knows how to create them?
I did find a .cfg file somewhere in the in the Model_* directories but those config files seem to have added numbers to variable names.

Can I generate a clean .cfg file somehow?

Example:
https://github.com/tlaplus/Examples/tree/master/specifications/Prisoners
https://github.com/tlaplus/Examples/blob/master/specifications/Prisoners/Prisoners.cfg

**Comment by lemmy** [comment]
@JordyMoos The TLA Toolbox creates the .cfg files from its visual model representation for you. You don't have to manually edit .cfg files at all.

**Comment by muenchnerkindl** [comment]
Hello Jordy, 

as Markus already said, the Toolbox creates the .cfg files for you. In the old days, users had to write .cfg files themselves (and this is still true if you use TLC from the command line): a TLA+ specification usually describes an infinite-state system (or a family of systems), and the configuration describes a finite-state instance of the system. Config files are described in "Specifying Systems", but for all practical purposes, you don't have to worry about them today. 

Regards, 
Stephan

**Comment by lemmy** [comment]
Two minor additions: 
1) The .cfg files - created by the Toolbox - define the variable values in the MC.tla instead of directly in MC.cfg. This is why you see those funny looking variable names in MC.cfg.
2) You can run command line TLC also on the MC.tla/MC.cfg generated by the Toolbox. Replace your spec's name with "MC", e.g. `java -jar tla2tools.jar MC`

**Comment by younes-io** [comment]
Hello @lemmy ,
Do you know of any way to generate these files without the command line?
Thank you,

**Comment by FedericoPonzi** [comment]
> Trying to follow the "Getting started" ( https://docs.tlapl.us/using:vscode:getting_started) and it fails on the step Check Model step as the cfg file is missing. Should the guide be updated?

Thanks for spotting - vscode plugin was [updated](https://github.com/tlaplus/vscode-tlaplus/commit/9b370538daf8de7cb6228fe4c0fd94c8a0a680b8) to not generate the .cfg file for pluscal. The change is explained [here](https://github.com/tlaplus/vscode-tlaplus/issues/293). The documentation is outdated so it will need to be updated. I can do it later or feel free to give it a stab at it.

A minimal .cfg file for squares is:
```
SPECIFICATION Spec
```
When there is no .cfg file, you can also run the action "Check model with TLC". If the .cfg file is missing you will get these notifications on bottom right:

<img width="545" height="228" alt="Image" src="https://github.com/user-attachments/assets/c07ab104-e45c-43e3-bbc1-29a32cad6c74" />

you can click on `Create model file` to generate a `.cfg` file from a predefined template.

> Perhaps related: the "Getting Started" page points to a "troubleshooting" page at https://docs.tlapl.us/using:vscode:alygin_vscode-tlaplus_wiki_troubleshooting, which is probably not the correct URL.

Thanks for spotting, this is fixed now. I'll double check the vscode pages for broken links later.
