### ISSUE TITLE
Running the N-Queens example on Linux fails because filename is Pluscal not PlusCal

### ISSUE THREAD

**Issue by zeonglow** [tlaplus/Examples#7]
I fixed this myself by renaming some files, I don't yet have the woo to make a pull request.  I have absolutely no idea what I am doing BTW,  I was just trying out an example to test I had installed the TLA Toolbox correctly.

**Comment by lemmy** [comment]
Thanks for the report, fixed with commit 3567f985605d0dc340b55c7f4f66883dc7b3eed2
