### ISSUE TITLE
Parameterize version of TLA+ tools used during CI run

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/Examples#77]
@lemmy in an earlier issue you mentioned it would be useful to parameterize the version of the TLA+ tools used during the CI run, so you could for example trigger a build of the tlaplus/tlaplus repo and have the resulting binary be used during a CI run for the tlaplus/examples repo. Are you still interested in this feature? Will look into implementing it if so.

**Comment by lemmy** [comment]
It would be beneficial to replace the [old PR integration](https://github.com/tlaplus/tlaplus/blob/master/.github/workflows/pr.yml#L42-L57) between `tlaplus/tlaplus` and `tlaplus/example`. Additionally, if [main.yml](https://github.com/tlaplus/tlaplus/blob/master/.github/workflows/main.yml) were set to trigger a run of `tlaplus/example`, it would provide us with a historical record.

**Comment by lemmy** [comment]
FYI: The integration between `tlaplus/tlaplus` and `tlaplus/vscode-tlaplus` relies on [peter-evans/repository-dispatch@v2Github ](https://github.com/peter-evans/repository-dispatch).
