### ISSUE TITLE
CI workflow fails on ubuntu

### ISSUE THREAD

**Issue by muenchnerkindl** [tlaplus/Examples#82]
After merging a bug fix for one of the examples (aba-asyn-byz), the CI run succeeded for Windows and Mac OS but failed for Ubuntu due to an error in generating the Isabelle object logic heap. Why is this happening? Also, the updated example doesn't contain any proofs so the problem is clearly unrelated to the fix.

@ahelwer, could you please have a look?

**Comment by ahelwer** [comment]
There's an option in the workflow to re-run it. Looks like an issue with the TLAPS install, so probably there is some rare instance where the installation step fails nondeterministically.

**Comment by lemmy** [comment]
TLAPS apparently also has an install failure on Windows, which causes the [last two CI](https://github.com/tlaplus/Examples/actions/runs/5629313837) runs to fail:

```
2023-07-22 06:53:02 (13.9 MB/s) - ‘202210041448.tar.gz’ saved [11231483]

tar: tlapm-202210041448/zenon/regression/examples/data/TLAPS.tla: Cannot change mode to rwxr-xr-x: Not a directory
tar: Exiting with failure status due to previous errors
Error: Process completed with exit code 2.
```

**Comment by ahelwer** [comment]
That might be an issue with tar as packaged by cygwin, will take a look.

**Comment by ahelwer** [comment]
@lemmy looks like your latest changes broke the workflow?

**Comment by lemmy** [comment]
EWD998Small.cfg finished in 24s on my machine, which is within the 30s timeout.  Do I just increment the timeout?

**Comment by ahelwer** [comment]
There are actually two issues:
1. In Windows CI, EWD998Small.cfg hit hard timeout; the timeout is 60 seconds as set [here](https://github.com/tlaplus/Examples/blob/e4b3677cc1fa76db40f45793546f5992154d2a6c/.github/scripts/check_small_models.py#L49). On both macOS and Linux it finished in 27 seconds. Maybe this is transient/nondeterministic or it runs differently on windows?
2. On macOS and Linux there is an error when smoke-testing large models where model specifications/ewd998/EWD998ChanID.cfg expected error code 0 but got 11 (deadlock failure). So maybe you need to add "ignore deadlock" to its config in the manifest?

**Comment by ahelwer** [comment]
Recommend closing this in favor of https://github.com/tlaplus/tlapm/issues/88
