### ISSUE TITLE
Remove deadlock flag in manifest.json in favor of `CHECK_DEADLOCK` in config file

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/Examples#98]
Recently learned about `CHECK_DEADLOCK` being an option in model files. Currently whether to check deadlock for each model is defined in the manifest.json, for example:
```json
{
  "path": "specifications/Huang/Huang.cfg",
  "runtime": "00:00:40",
  "size": "medium",
  "mode": "exhaustive search",
  "config": [
    "ignore deadlock"
  ],
  "features": [
    "alias",
    "liveness",
    "state constraint"
  ],
  "result": "success"
}
```
which the Python script reads then passes on to the TLC command line flags. I think it would be better to remove this config item in favor of `CHECK_DEADLOCK` in the model file.

**Comment by ahelwer** [comment]
@lemmy is there a similar model file parameter for running in simulation mode or trace generation mode? Or even something like an `EXPECT SAFETY_FAILURE` type parameter?

**Comment by lemmy** [comment]
`CHECK_DEADLOCK` is recognized by all TLC modes.  There is nothing like `EXPECT SAFETY_FAILURE`.  https://github.com/tlaplus/tlaplus/issues/827 is related.

**Comment by ahelwer** [comment]
Oh I mean is it possible to specify TLC check mode as a parameter in the model? Like `EXECUTION_MODE SIMULATE` or something.

**Comment by lemmy** [comment]
No
