### ISSUE TITLE
Install TLA+ unicode converter into gitpod and codespaces

### ISSUE THREAD

**Issue by lemmy** [tlaplus/Examples#99]
https://github.com/tlaplus-community/tlauc should be installed as part of https://github.com/tlaplus/Examples/blob/master/.devcontainer/install.sh.

/cc @ahelwer

**Comment by ahelwer** [comment]
This can be done with
```bash
wget -nv https://github.com/tlaplus-community/tlauc/releases/latest/download/tlauc-linux.tar.gz
tar -xzf tlauc-linux.tar.gz
```
